# $FreeBSD$

.include <bsd.own.mk>

LIB=    lldlibCore

SRCDIR=	tools/lld/lib/Core
SRCS=   DefinedAtom.cpp \
	Error.cpp \
	File.cpp \
	LinkingContext.cpp \
	Reader.cpp \
	Resolver.cpp \
	SymbolTable.cpp \
	Writer.cpp

.include "../lld.lib.mk"
