# $FreeBSD$

SUBDIR+=		efi
SUBDIR+=		libstand32
SUBDIR+=		zfs
SUBDIR+=		userboot

.if ${MK_FORTH} != "no"
SUBDIR+=		ficl32
.endif

# most/all i386 bootloaders fail due to lack of -N support in lld
#SUBDIR+=		i386
